# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-08-31 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('os', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('last_connection', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=500)),
                ('answer', models.CharField(blank=True, max_length=200)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Bot')),
            ],
        ),
    ]
