# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-03 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_task_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Bot')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='bot',
        ),
        migrations.AddField(
            model_name='task',
            name='total_workers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='task',
            name='workers_running',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Task'),
        ),
    ]
