# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-09-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='current_state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
